### ISSUE TITLE
[FR] Project Examples for PlatformIO Registry

### ISSUE THREAD

**Issue by Ste-Trat** [arduino-libraries/Arduino_CMSIS-DSP#2]
Hi,

Currently, the [library page](https://registry.platformio.org/libraries/arduino-libraries/Arduino_CMSIS-DSP) in the PlatformIO Registry doesn't contain any quick start projects for developers. Such examples serve both to highlight widespread use cases and to help newcomers to get up and running much more quickly.

Please consider adding a few comprehensive project examples to the PlatformIO Registry.

Useful links:
- https://registry.platformio.org/libraries/arduino-libraries/Arduino_CMSIS-DSP
- https://docs.platformio.org/en/latest/librarymanager/config.html#examples

**Comment by aentinger** [comment]
Hi @Ste-Trat ☕ :wave:

I understand what you are saying but this library is not really meant to be used as-is. Instead it's required for some other library to run, possibly @facchinm could fill me in which, then I'll update this libraries README accordingly.

**Comment by facchinm** [comment]
Yup, this library has been created to overcome a problem on mbed-os based platforms + TensorflowLite.

Background: mbed-os used to ship a version of CMSIS-DSP, so the boards already had it shipped with the core.
Then, they removed the code but left the headers, making libraries that use DSP function quite confused :slightly_smiling_face: 

This library fills the gap providing the implementation but there's no need to add examples since the standalone usage is discouraged.
